spring:
 datasource:
  url: jdbc:mysql://localhost:3306/order_management
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: test
 cloud:
     stream:
          default-binder: kstream
          bindings:
           processOrder-in-0:
            group: orderConsumerGroup
            destination: order-in-topic
            content-type: application/json
           processOrder-out-0:
            destination: electronics-order-out-topic
            content-type: application/json
           processOrder-out-1:
            destination: grocery-order-out-topic
            content-type: application/json
          function:
                definition: processOrder
     kafka:
         binder:
              brokers: localhost:9092




 application:
  name: hello-order-details

  
  
  
